### ISSUE TITLE
Future HD Space Issue

### ISSUE THREAD

**Issue by swt83** [ayeowch/bitnodes-hardware#1]
If I run this for a few years, and the Blockchain gets huge, will I be able to plug in an external HD to keep it going?

Nice work on this.

**Comment by ayeowch** [comment]
I have documented the steps to use USB drive here: https://forum.bitnodes.io/t/using-a-usb-drive-instead-of-microsd/25/1

**Comment by swt83** [comment]
My device is "stopped" and I think this is the issue why.  I guess I'm going to add a USB drive and move things over using your link above.

It's amazing how big the blockchain has gotten in only a few months.

**Comment by ayeowch** [comment]
Indeed the 64GB microSD shipped with first version of B1 is at capacity now.

I have posted instructions on upgrading to 128GB microSD in https://forum.bitnodes.io/t/node-stops-almost-every-other-day/90/6?u=ayeowch
