### ISSUE TITLE
Feature request: Buttons on display to trigger shutdown/reboot

### ISSUE THREAD

**Issue by rossigee** [ayeowch/bitnodes-hardware#6]
As per the following forum thread...

https://forum.bitnodes.io/t/buttons-on-the-side-of-the-monitor/60/4

I think this would be a very useful feature. If anyone can provide pointers on how to approach a PR for this, I'd gladly look further into it (experienced dev, but embedded noob).

**Comment by ayeowch** [comment]
See http://odroid.com/dokuwiki/doku.php?id=en:c1_tft_keypads
